# Copyright 2018 Google LLC All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.agones.crds.install }}

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: fleetautoscalers.autoscaling.agones.dev
  labels:
    component: crd
    app: {{ template "agones.name" . }}
    chart: {{ template "agones.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: autoscaling.agones.dev
  version: v1
  scope: Namespaced
  names:
    kind: FleetAutoscaler
    plural: fleetautoscalers
    shortNames:
    - fas
    singular: fleetautoscaler
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - fleetName
            - policy
          properties:
            fleetName:
              type: string
              minLength: 1
              maxLength: 63
              pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
            policy:
              required:
                - type
              properties:
                type:
                  type: string
                  enum:
                  - Buffer
                  - Webhook
                buffer:
                  required:
                    - maxReplicas
                  properties:
                    minReplicas:
                      type: integer
                      minimum: 0
                    maxReplicas:
                      type: integer
                      minimum: 1
                webhook:
                  properties:
                    service:
                      properties:
                        name:
                          type: string
                        namespace:
                          type: string
                        path:
                          type: string
                    url:
                      type: string
                    caBundle:
                      type: string
  subresources:
    # status enables the status subresource.
    status: {}
{{- end }}
